**Theoretocal Questions:**

**1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?**

**Ans.**

**Purposes:**

**1. Efficient Numerical Computations:** NumPy provides highly efficient and optimized operations for numerical computations, essential for scientific computing.

**2. Array Manipulation:** It introduces the powerful N-dimensional array object, which allows for efficient storage and manipulation of large datasets.

**3. Mathematical Functions:** NumPy includes a comprehensive set of mathematical functions for operations like linear algebra, Fourier transform, and random number generation.


**Advantages:**

**1. Performance:** NumPy's array operations are significantly faster than Python's built-in lists, due to its optimized C and Fortran implementations.

**2. Memory Efficiency:** Arrays in NumPy are more memory-efficient compared to lists, as they store elements of the same data type.

**3. Broad Functionality:** The library includes a wide range of functions for statistical, algebraic, and mathematical operations.

**4. Integration:** NumPy seamlessly integrates with other scientific computing libraries like SciPy, Matplotlib, and pandas.

**5. Ease of Use:** Its syntax and functions are designed to be intuitive and easy to use, making it accessible for beginners and powerful for experts.

**6. Community and Support:** NumPy is widely used in both academia and industry, with extensive documentation and a large, active user community.


**Enhancements to Python:**

**1. Vectorization:** NumPy allows for vectorized operations, which means you can perform element-wise operations on arrays without writing explicit loops. This not only makes the code more concise but also enhances performance.

**2. Broadcasting:** It supports broadcasting, a mechanism that allows arrays of different shapes to be used in arithmetic operations without the need to reshape them manually.

**3. Interoperability:** NumPy arrays can be used in conjunction with other libraries like TensorFlow for machine learning, making it a cornerstone of the Python scientific stack.

**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?**

**Ans.**

**np.mean():**

**Purpose:** Computes the arithmetic mean (average) of array elements along a specified axis.

**Syntax:** np.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)

**Parameters:**

**a:** Array-like object containing the numbers.

**axis:** Axis or axes along which the means are computed. By default, the mean is computed of the flattened array.

**dtype:** Data type of the result.

**out:** Alternative output array to place the result.

**keepdims:** If True, the reduced axes are left in the result as dimensions with size one.

**`Weighted Average:** Does not support weighted averages. It only computes the simple arithmetic mean.

**np.average():**

**Purpose:** Computes the weighted average of array elements along a specified axis.

**Syntax:** np.average(a, axis=None, weights=None, returned=False)

**Parameters:**

**a:** Array-like object containing the numbers.

**axis:** Axis or axes along which the averages are computed. By default, the average is computed of the flattened array.

**weights:** An array of weights associated with the values in a. The weights array can either be 1-D or of the same shape as a.

**returned:** If True, returns a tuple containing the average and the sum of the weights.

**Weighted Average:** Supports weighted
averages. If weights are provided, it computes the weighted average; if weights are None, it acts like np.mean().

**When to Use One Over the Other**



*   **Use** np.mean():


1.   When you need to compute the simple arithmetic mean of elements without any weighting.
2.   When you want a straightforward and simple way to calculate the average.


3.  Examples: General statistics, calculating the mean temperature of a dataset, etc




*   **Use** np.average():



1.  When you need to compute a weighted average, where different elements have different levels of importance or frequency.
2.   When you want a straightforward and simple way to calculate the average.


3.   Examples: Calculating the average score of a student where different subjects have different credits, finding the average of a dataset with varying significance of values, etc.



**3.  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.**

**Ans.**

Reversing a NumPy array along different axes can be done efficiently using slicing and the np.flip() function.

In [ ]:
#1D Array
#Using slicing

import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
reversed_array_1d = array_1d[::-1]

print("Original 1D Array:", array_1d)
print("Reversed 1D Array:", reversed_array_1d)


Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]


In [ ]:
#Using np.flip()

reversed_array_1d_flip = np.flip(array_1d)

print("Reversed 1D Array using np.flip():", reversed_array_1d_flip)


Reversed 1D Array using np.flip(): [5 4 3 2 1]


In [ ]:
#2D Array
#Reversing Along Rows (Axis 0)

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = array_2d[::-1, :]

print("Original 2D Array:\n", array_2d)
print("Reversed Rows (Axis 0):\n", reversed_rows)


Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed Rows (Axis 0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
#Reversing Along Columns (Axis 1)

reversed_columns = array_2d[:, ::-1]

print("Reversed Columns (Axis 1):\n", reversed_columns)


Reversed Columns (Axis 1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
#Reversing Along Both Axes

reversed_both_axes = array_2d[::-1, ::-1]

print("Reversed Both Axes:\n", reversed_both_axes)


Reversed Both Axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#Using np.flip() Along a Specific Axis

reversed_rows_flip = np.flip(array_2d, axis=0)
reversed_columns_flip = np.flip(array_2d, axis=1)

print("Reversed Rows using np.flip() (Axis 0):\n", reversed_rows_flip)
print("Reversed Columns using np.flip() (Axis 1):\n", reversed_columns_flip)


Reversed Rows using np.flip() (Axis 0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed Columns using np.flip() (Axis 1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


**4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

**Ans.**



1.  **Memory Management:**

**Size:** Different data types occupy different amounts of memory. For example, int32 occupies 4 bytes per element, while int64 occupies 8 bytes. Using the appropriate data type can significantly reduce memory usage.

**Precision:** Choosing data types that match the precision requirements of your application ensures efficient memory usage without compromising accuracy. For instance, if you only need to store values between 0 and 255, using an uint8 (1 byte) is more efficient than using a float64 (8 bytes).

2.   **Performance:**

**Speed:** Operations on smaller data types are generally faster because they require less memory to be accessed and processed. For instance, computations with int32 are often faster than with int64.

**Vectorization:** NumPy leverages low-level optimizations and vectorized operations that work directly on arrays. Using the right data types ensures that these optimizations are applied effectively, leading to faster computations.



**5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Ans.**

In NumPy, an ndarray is the primary data structure for storing large, multi-dimensional homogeneous data. It is a powerful object that provides a way to perform numerical operations on large datasets with high efficiency.

**Key Features of ndarray**



1.   **N-dimensional:** As the name suggests, ndarray can handle data of arbitrary dimensions, from 1D arrays to n-dimensional arrays (e.g., 2D for matrices, 3D for tensors).

2.  **Homogeneous:** All elements in an ndarray are of the same data type. This makes operations on the array more efficient as the underlying data storage is optimized for a single type.

3.   **Shape and Size:** The shape attribute provides the dimensions of the array (e.g., rows and columns for a 2D array). The size attribute gives the total number of elements in the array.
4.   **Efficient Operations:** NumPy provides a suite of functions optimized for fast numerical operations on arrays, including arithmetic operations, statistical operations, and more.


5.   **Slicing and Indexing:** ndarray supports advanced slicing and indexing techniques for accessing and modifying parts of the array efficiently


6.  **Broadcasting:** NumPy allows arithmetic operations to be performed on arrays of different shapes, automatically expanding one array to match the shape of the other (if possible).

**Differences Between ndarray and Python Lists**

1.   **Performance:**

**NumPy ndarray:** Optimized for numerical operations with a significant performance boost due to low-level optimizations (e.g., vectorized operations).

**Python Lists:** General-purpose data structures not optimized for numerical operations, leading to slower performance for large datasets.

2.   **Memory Efficiency:**

**NumPy ndarray:** Stores elements in contiguous blocks of memory, leading to more efficient storage and better cache performance.

**Python Lists:** Store elements as references to objects, leading to additional overhead and less efficient memory usage.


3.   **Homogeneity:**

**NumPy ndarray:** Elements must be of the same data type, which allows for optimized operations.

**Python Lists:** Can store elements of different data types, offering more flexibility but less efficiency for numerical computations.
4.   **Advanced Operations:**

**NumPy ndarray:** Supports a wide range of mathematical and statistical operations, including linear algebra, Fourier transforms, and random number generation.

**Python Lists:** Limited in terms of built-in numerical operations and require manual implementation or external libraries for advanced tasks.

**6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

**Ans.**


1.   **Speed**



*   **Vectorization:** NumPy utilizes highly optimized C and Fortran libraries, allowing for vectorized operations. This means operations can be performed element-wise on entire arrays simultaneously, rather than looping through elements.
*   **Less Overhead:** NumPy arrays are more compact and use contiguous blocks of memory, reducing the overhead that comes with the dynamic typing and memory allocation of Python lists.


2.   **Memory Efficiency:**



*   **Fixed Data Types:** NumPy arrays store elements of the same data type, leading to more efficient memory usage compared to Python lists that can hold elements of different data types.
*   **Compact Storage:** NumPy arrays use less memory for storing data as they require a contiguous block of memory, whereas Python lists may need additional memory for pointers.



3.  ** Functionality:**



1.   **Broad Set of Functions:** NumPy provides a comprehensive set of functions and methods for numerical operations, matrix manipulations, and linear algebra that are not available with standard Python lists.
2.   **Convenience:** Operations like matrix multiplication, element-wise operations, and broadcasting are more straightforward and concise with NumPy arrays.


4.   **Interoperability:**



1.   **Integration with Libraries:** NumPy arrays are the foundation of many other scientific and data analysis libraries in Python, such as Pandas, SciPy, and scikit-learn. This makes data exchange and processing more efficient and consistent.






5.   **Parallelism and Optimization:**



1.   **Parallel Execution:** NumPy can leverage multiple CPU cores for parallel execution, making it more efficient for large-scale computations.
2.  **Optimization Techniques:** NumPy employs various optimization techniques like in-place operations to further improve performance.






**7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.**

**Ans.**


*  **vstack() Function**

The vstack() function stacks arrays vertically (row-wise). It combines arrays along the vertical axis to form a larger array.
*   **hstack() Function**


The hstack() function stacks arrays horizontally (column-wise). It combines arrays along the horizontal axis to form a larger array.



*   Comparison Summary:


*   **vstack():** Stacks arrays vertically (row-wise), increasing the number of rows.
*   **hstack():** Stacks arrays horizontally (column-wise), increasing the number of columns.







In [1]:
#vstack() Function

import numpy as np

# Creating two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Using vstack() to stack arrays vertically
result_vstack = np.vstack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nVertically Stacked Array:")
print(result_vstack)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Vertically Stacked Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
#hstack() Function

import numpy as np

# Creating two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Using hstack() to stack arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nHorizontally Stacked Array:")
print(result_hstack)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Horizontally Stacked Array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.**

**Ans.**


*   **fliplr() Method**

The fliplr() method flips an array left to right (horizontally). It reverses the order of columns, leaving the rows unchanged.
*   **flipud() Method**

The flipud() method flips an array upside down (vertically). It reverses the order of rows, leaving the columns unchanged.



*   **Differences and Effects on Array Dimensions**



1.   **fliplr()**

**Effect:** Reverses the order of columns.

**Usage:** Primarily used for flipping arrays horizontally.

**Array Dimension:** Works on 2D arrays and higher-dimensional arrays where the operation is applied to the last dimension.


2.   **flipud()**


**Effect:** Reverses the order of rows.

**Usage:** Primarily used for flipping arrays vertically.

**Array Dimension:** Works on 2D arrays and higher-dimensional arrays where the operation is applied to the first dimension.





**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

**Ans.**

The array_split() method in NumPy is a versatile function used to split an array into multiple sub-arrays. It is especially handy when you need to divide an array into uneven sections, unlike split(), which requires evenly divisible sections.

*   **Functionality of array_split()**

**Usage:** numpy.array_split(ary, indices_or_sections, axis=0)

**Parameters:**

**ary:** The input array to be split.

**indices_or_sections:** Either an integer indicating the number of equal divisions or a list of indices at which to split the array.

**axis:** The axis along which to split the array. By default, it splits along axis 0 (rows).
*  **Handling Uneven Splits**

When the array cannot be split into equal-sized sub-arrays, array_split() ensures that the sub-arrays are as close in size as possible. This means that some sub-arrays may be larger than others, but the difference will be minimal.

**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

**Ans.**

**Vectorization**

Vectorization refers to the process of applying operations to entire arrays or large blocks of data in a single step, rather than iterating through individual elements. This leverages low-level optimizations and highly efficient C and Fortran libraries, making operations much faster and more concise.

**Benefits:**



*   **Speed:** Vectorized operations are often orders of magnitude faster than their non-vectorized counterparts, thanks to underlying optimized implementations.
*   **Readability:** Code becomes cleaner and easier to understand, reducing the need for explicit loops.

**Broadcasting**

Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. When performing operations, NumPy automatically expands the smaller array to match the dimensions of the larger array, without making extra copies of data.

**Rules:**



1.   If the arrays differ in their number of dimensions, the shape of the smaller array is padded with ones on its left side.
2.   If the shape of the arrays differ in a dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.



3.  If the shapes of the arrays do not match and the difference is not equal to 1, a ValueError is raised.


**How They Contribute to Efficient Array Operations:**



*   **Performance:** Both vectorization and broadcasting eliminate the need for explicit loops, enabling efficient execution of operations using low-level optimizations.
*   **Memory Efficiency:** Broadcasting avoids unnecessary data replication, saving memory and improving performance.




*   **Simplified Code:** They make code more concise and readable, reducing the chance of errors and improving maintainability.





**Practical Questions:**

**Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

**Ans.**



In [3]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array)

# Transposing the array
transposed_array = np.transpose(array)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[27 50 91]
 [68 69 10]
 [58 56 89]]

Transposed Array:
[[27 68 58]
 [50 69 56]
 [91 10 89]]


**2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

**Ans.**



In [4]:
import numpy as np

# Generating a 1D array with 10 elements
array_1d = np.arange(10)

print("Original 1D Array:")
print(array_1d)

# Reshaping the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

print("\nReshaped 2x5 Array:")
print(array_2x5)

# Reshaping the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("\nReshaped 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

**Ans.**



In [5]:
import numpy as np

# Creating a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Adding a border of zeros around the 4x4 array to form a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\nArray with Border of Zeros (6x6):")
print(array_6x6)


Original 4x4 Array:
[[0.2488513  0.76871126 0.18409629 0.75058261]
 [0.53590244 0.06462922 0.96132484 0.27787845]
 [0.98533835 0.78479158 0.17687794 0.81632367]
 [0.96732651 0.0785411  0.26066779 0.55014245]]

Array with Border of Zeros (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.2488513  0.76871126 0.18409629 0.75058261 0.        ]
 [0.         0.53590244 0.06462922 0.96132484 0.27787845 0.        ]
 [0.         0.98533835 0.78479158 0.17687794 0.81632367 0.        ]
 [0.         0.96732651 0.0785411  0.26066779 0.55014245 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

**Ans.**




In [6]:
import numpy as np

# Creating an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array from 10 to 60 with a step of 5:")
print(array)


Array from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

**Ans.**



In [7]:
#Creating the Array:
import numpy as np

# Creating a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

print("Original Array:")
print(array)


Original Array:
['python' 'numpy' 'pandas']


In [8]:
#Uppercase Transformation:

array_upper = np.char.upper(array)

print("\nUppercase Array:")
print(array_upper)



Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']


In [9]:
#Lowercase Transformation:

# Lowercase transformation
array_lower = np.char.lower(array)

print("\nLowercase Array:")
print(array_lower)



Lowercase Array:
['python' 'numpy' 'pandas']


In [10]:
#itle Case Transformation:

# Title case transformation
array_title = np.char.title(array)

print("\nTitle Case Array:")
print(array_title)



Title Case Array:
['Python' 'Numpy' 'Pandas']


In [11]:
import numpy as np

# Creating a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

print("Original Array:")
print(array)

# Uppercase transformation
array_upper = np.char.upper(array)
print("\nUppercase Array:")
print(array_upper)

# Lowercase transformation
array_lower = np.char.lower(array)
print("\nLowercase Array:")
print(array_lower)

# Title case transformation
array_title = np.char.title(array)
print("\nTitle Case Array:")
print(array_title)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Title Case Array:
['Python' 'Numpy' 'Pandas']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

**Ans.**



In [13]:
import numpy as np

# Creating a NumPy array of words
words_array = np.array(['hello', 'world', 'sanket'])

print("Original Array:")
print(words_array)

# Inserting a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print("\nArray with Spaces between Characters:")
print(spaced_words_array)


Original Array:
['hello' 'world' 'sanket']

Array with Spaces between Characters:
['h e l l o' 'w o r l d' 's a n k e t']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

**Ans.**

In [14]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Element-wise addition
addition_result = np.add(array1, array2)
print("\nElement-wise Addition Result:")
print(addition_result)

# Element-wise subtraction
subtraction_result = np.subtract(array1, array2)
print("\nElement-wise Subtraction Result:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = np.multiply(array1, array2)
print("\nElement-wise Multiplication Result:")
print(multiplication_result)

# Element-wise division
division_result = np.divide(array1, array2)
print("\nElement-wise Division Result:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition Result:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction Result:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication Result:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division Result:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


**8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

**Ans.**


In [15]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extracting the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.**

**Ans.**

In [16]:
import numpy as np

# Generating an array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

print("Random Array:")
print(random_array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Finding prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Array:
[711 488 335 964 702 353 439 715 426 672 208 475 242 635 447 474 444 409
 131 880 699 969 862 588 466  31 754 759 953  48 101 644 122 200 269 421
 460 216  65 330 670 681 974 853 731 102 618 572 160 359 427 950 291 648
 481 126 600 171 742 896 771 350 443 210 203  44 145 224 992 603 654 707
 638 222 136  71 490 844 801 170 998 948 330 833 626  17 523  90 906 870
 488 141 180 109 538 293 499 532 829 249]

Prime Numbers in the Array:
[353, 439, 409, 131, 31, 953, 101, 269, 421, 853, 359, 443, 71, 17, 523, 109, 293, 499, 829]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

**Ans.**



In [28]:
import numpy as np

# Generating an array representing daily temperatures for 30 days
daily_temperatures = np.random.randint(20, 35, size=30)  # Random temperatures between 20 and 35 degrees Celsius

print("Daily Temperatures for a Month:")
print(daily_temperatures)

# Splitting the array into weeks (4 weeks + 2 extra days)
weeks = np.split(daily_temperatures[:28], 4)  # First 28 days for 4 weeks
extra_days = daily_temperatures[28:]  # Remaining 2 days

# Calculating the weekly averages
weekly_averages = [np.mean(week) for week in weeks]

# If there are extra days, calculate their average
if extra_days.size > 0:
    weekly_averages.append(np.mean(extra_days))

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for a Month:
[23 26 24 29 34 20 30 33 23 28 28 23 34 26 34 25 31 29 27 25 20 29 30 24
 31 28 28 26 25 24]

Weekly Averages:
[26.571428571428573, 27.857142857142858, 27.285714285714285, 28.0, 24.5]
